# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
 # Ensure that your git status is not dirty
  ensure_git_status_clean

  # Increment the build number (not the version number)
  # Providing the xcodeproj is optional
  increment_build_number(
    build_number: latest_testflight_build_number + 1,
    xcodeproj: "BGRecordingTestApp.xcodeproj"
  )

  # Commit the version bump
  commit_version_bump(xcodeproj: "BGRecordingTestApp.xcodeproj")

  # Add a git tag for this build. This will automatically
  # use an appropriate git tag name
  add_git_tag

  # Push the new commit and tag back to your git remote
  push_to_git_remote
slack(message: "Started New beta build")

    build_app(workspace: "BGRecordingTestApp.xcworkspace", scheme: "BGRecordingTestApp")
    upload_to_testflight
slack(message: "Successfully distributed a new beta build, check it out!")
  end

lane :beta_test do
 # Ensure that your git status is not dirty
  ensure_git_status_clean

  # Increment the build number (not the version number)
  # Providing the xcodeproj is optional
  increment_build_number(
    build_number: latest_testflight_build_number + 3,
    xcodeproj: "BGRecordingTestApp.xcodeproj"
  )

  # Commit the version bump
  commit_version_bump(xcodeproj: "BGRecordingTestApp.xcodeproj")

  # Add a git tag for this build. This will automatically
  # use an appropriate git tag name
  add_git_tag
slack(message: "Started New beta build")
  # Push the new commit and tag back to your git remote
  push_to_git_remote


    build_app(workspace: "BGRecordingTestApp.xcworkspace", scheme: "BGRecordingTestApp")
    upload_to_testflight
slack(message: "Successfully distributed a new beta build, check it out!")
  end

end
